server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/lagou?characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8

mybatis-plus:
  type-aliases-package: com.lagou.dockerdemo.entity
  mapper-locations: mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl






